### ISSUE TITLE
SOAP with multiple species

### ISSUE THREAD

**Issue by bartolsthoorn** [epfl-cosmo/glosim#10]
Hi,

I have three questions regarding SOAP with multiple species:

1. Does the `--kernel fastavg` take different species into account? Looking at the definition it does not seem to be the case:

![screenshot from 2018-09-06 14-57-52](https://user-images.githubusercontent.com/106586/45158761-47800700-b1e5-11e8-87e8-60544b7d534e.png)

2. I would like to take the different species into account with the kronecker delta function, i.e.:
![screenshot from 2018-09-06 15-05-27](https://user-images.githubusercontent.com/106586/45159147-53b89400-b1e6-11e8-84bc-85b23d96b746.png)
Is `--kernel fastspecies` the way to go? It seems it requires environmental information (a lot of RAM) so it is not comparable with fastavg in that sense. Are the `--kernel average` and `--kernel rematch` also taking into account different species with a delta function, and if so, how is it different from `--kernel fastspecies`?

3. It seems like the `--separate_species` flag is about the specie of the centers, not actually about taking the species in the environment into account. When it is recommended to use this?

**Comment by ceriottm** [comment]
On Thu, 6 Sep 2018 at 16:15, Bart Olsthoorn <notifications@github.com>
wrote:

> Hi,
>
> I have three questions regarding SOAP with multiple species:
>
>    1. Does the --kernel fastavg take different species into account?
>    Looking at the definition it does not seem to be the case:
>
> [image: screenshot from 2018-09-06 14-57-52]
> <https://user-images.githubusercontent.com/106586/45158761-47800700-b1e5-11e8-87e8-60544b7d534e.png>
>

It does, in this definition \bf p also contains the alpha beta indices


>
> <https://user-images.githubusercontent.com/106586/45158761-47800700-b1e5-11e8-87e8-60544b7d534e.png>
>
>    1.
>
>    I would like to take the different species into account with the
>    kronecker delta function, i.e.:
>    [image: screenshot from 2018-09-06 15-05-27]
>    <https://user-images.githubusercontent.com/106586/45159147-53b89400-b1e6-11e8-84bc-85b23d96b746.png>
>    Is --kernel fastspecies the way to go? It seems it requires
>    environmental information (a lot of RAM) so it is not comparable with
>    fastavg in that sense. Are the --kernel average and --kernel rematch
>    also taking into account different species with a delta function, and if
>    so, how is it different from --kernel fastspecies?
>
> all the kernels treat species separately, the different from average and
fastavg is that average allows you to use non-linear kernels while with
fastavg you're limited to the linear case


>
>    1.
>    2.
>
>    It seems like the --separate_species flag is about the specie of the
>    centers, not actually about taking the species in the environment into
>    account. When it is recommended to use this?
>
> It is kind of untested, so just don't use it. It is equivalent to learning
a separate energy function for each species. fastpecies does something like
that, but it's largely untested too.

**Comment by bartolsthoorn** [comment]
Thank you, this clarifies things a lot! We obtained good results with the `fastavg` kernel.
