### ISSUE TITLE
When to use unnormalized SOAPs

### ISSUE THREAD

**Issue by bartolsthoorn** [epfl-cosmo/glosim#9]
Hi all,

I noticed the new flag `--unsoap` was added to use unnormalized SOAPs, when do you recommend to use this flag?

Best regards,
Bart

**Comment by ceriottm** [comment]
Never. It generally hurts as it makes the kernel strictly 3-body. We were using it only as for testing
Michele

**Comment by bartolsthoorn** [comment]
OK good to know, thank you!
